set(CMAKE_SYSTEM_NAME Windows CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER /usr/bin/x86_64-w64-mingw32-gcc CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER /usr/bin/x86_64-w64-mingw32-g++ CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER /usr/bin/x86_64-w64-mingw32-windres CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
